pipeline {

    agent any

    environment {
        IMAGE_NAME = "vadivelu123/parking_app_helm"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Set Image Tag') {
            steps {
                script {
                    env.IMAGE_TAG = "build-${env.BUILD_NUMBER}"
                }

                echo "Image Tag: ${env.IMAGE_TAG}"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} parking-app-app/"
            }
        }

        stage('Login & Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {

                    sh """
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Update Helm Values (GitOps Repo)') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_TOKEN'
                )]) {

                    sh """
                    rm -rf gitops-repo
                    git clone git@github.com:vadivelu-dev/helm_argo.git gitops-repo

                    cd gitops-repo/helm/parking-app

                    echo "Before update:"
                    cat values.yaml

                    # UPDATE ONLY IMAGE TAG (HELM WAY)
                    sed -i 's/tag:.*/tag: ${IMAGE_TAG}/g' values.yaml

                    echo "After update:"
                    cat values.yaml

                    git config user.name "jenkins"
                    git config user.email "jenkins@ci.com"

                    git add values.yaml
                    git commit -m "Update image tag to ${IMAGE_TAG}"
                    git push origin main
                    """
                }
            }
        }
    }
}
